# Generated by Django 3.2.16 on 2022-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verificated',
            field=models.BooleanField(default=False),
        ),
    ]
