# Generated by Django 3.2.16 on 2022-11-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_verificated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banknumer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verificated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
