# Generated by Django 3.2.16 on 2022-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221111_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Forma_Wypłaty',
            field=models.CharField(blank=True, choices=[('gotówka', 'gotówka'), ('przelew', 'przelew')], max_length=100, null=True),
        ),
    ]
