# Generated by Django 3.2.16 on 2022-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221111_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Forma_Wypłaty',
            field=models.CharField(choices=[('gotówka', 'gotówka'), ('przelew', 'przelew')], default=True, max_length=100),
        ),
    ]
