# Generated by Django 3.2.16 on 2022-11-11 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rozliczenia_dataprzelewu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozliczenia',
            name='Inne_Koszty',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='Koszty_ZUS_I_Podatki',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='Prowizja_Partnera',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='Vat',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='Wypłata_Suma',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='Wypłata_Z_Tytułu_Najmu',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='Wypłata_Z_Tytułu_Zlecenia',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='rozliczenia',
            name='appname',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='rozliczenia',
            name='dataprzelewu',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 11, 59, 2, 735535, tzinfo=utc)),
        ),
    ]
