# Generated by Django 3.2.16 on 2022-11-11 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20221111_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozliczenia',
            name='dataprzelewu',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 12, 33, 18, 11903, tzinfo=utc)),
        ),
    ]
