# Generated by Django 3.2.16 on 2022-11-11 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20221111_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='typ_dokumentu',
            field=models.CharField(choices=[('Pasport', 'Paszport'), ('Legitimation', 'Legitymacja'), ('Visa/Residence Card', 'Wiza/Karta Pobytu'), ('Certificate of study', 'Zaświadczenie o studiach')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rozliczenia',
            name='dataprzelewu',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 14, 58, 36, 926819, tzinfo=utc)),
        ),
    ]
