# Generated by Django 3.2.16 on 2022-11-11 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20221111_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='dokument',
            field=models.FileField(default=0, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='rozliczenia',
            name='dataprzelewu',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 16, 34, 5, 291093, tzinfo=utc)),
        ),
    ]
