# Generated by Django 3.2.16 on 2022-11-11 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20221111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozliczenia',
            name='dataprzelewu',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 16, 34, 47, 867278, tzinfo=utc)),
        ),
    ]
