# Generated by Django 3.2.16 on 2022-11-11 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_rozliczenia_dataprzelewu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozliczenia',
            name='dataprzelewu',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 16, 42, 56, 108027, tzinfo=utc)),
        ),
    ]
